image: composer/composer:php5

before_script:
    - pecl install xdebug &>/dev/null
    - docker-php-ext-enable xdebug &>/dev/null
    - composer install &>/dev/null

"Lint: php":
    stage  : test
    script :
        - ./vendor/bin/phpcs --colors -p .

"Unit-tests":
    stage  : test
    script :
        - ./vendor/bin/phpunit --coverage-text --colors=never
