image: php:5.6

before_script:
    - apt-get update -yqq &>/dev/null
    - apt-get install git -yqq &>/dev/null
    - pecl install xdebug &>/dev/null
    - docker-php-ext-enable xdebug &>/dev/null
    - curl -sS https://getcomposer.org/installer | php &>/dev/null
    - php composer.phar install &>/dev/null

"Lint: php":
    stage  : test
    script :
        - ./vendor/bin/phpcs --colors -p .

"Unit-tests":
    stage  : test
    script :
        - php -i | grep curl
        - ./vendor/bin/phpunit --coverage-text --colors=never
