language : php
php      :
  - 7.1
  - 7.0
  - 5.6
  - 5.5
  - 5.4

sudo  : false
cache :
    directories:
        - vendor
        - $HOME/.composer/cache

before_script:
    - echo 'date.timezone = "Europe/Zurich"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - composer install --no-interaction

script: /vendor/bin/phpunit
