language : php
php      :
  - 7.1
  - 7.0
  - 5.6

sudo : false
env  :
    - COMPOSER_DISABLE_XDEBUG_WARN=1

cache :
    directories:
        - vendor
        - $HOME/.composer/cache

before_install:
    - echo 'date.timezone = "Europe/Zurich"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install:
    - travis_retry composer install --no-interaction --no-suggest

script:
    - ./vendor/bin/phpunit

after_success:
    - travis_retry php ./vendor/bin/coveralls -v
